exports.name = "Bandit"
exports.armure = "● ○ ○"
exports.rapidité = "● ● ●"
exports.description = "Ancien agent sous couverture ayant infiltré les Hannover Hells Angels, Brunsmeier est célèbre pour sa capacité à transformer les objets obsolètes en armes mortelles. Il a fabriqué un appareil pouvant électrifier le barbelé et les barricades, afin de blesser ou détruire tout ce qui les touche. Bandit peut placer ses charges à haute tension sur tous les gadgets métalliques, comme les barbelés, les murs renforcés et les boucliers déployables."
exports.url = "https://google.fr"
exports.capacité = "Fil électrifié (DISPOSITIF ÉLECTRIQUE RUSTIQUE CED-1)"
exports.ext=".gif"