exports.name = "Blackbeard"
exports.armure = "● ● ○"
exports.rapidité = "● ● ○"
exports.description = "Elevé dans le nord-ouest de l'Amérique du Nord au sein d'une famille d'enseignants, Craig \"Blackbeard\" Jension a rapidement développé une passion pour tout ce qui touche au domaine militaire. Il a tout fait pour devenir un Navy SEAL, les voyant comme le mix parfait entre force physique et morale. Avec son bouclier d'arme blindé transparent TARS Mk 0, Blackbeard augmente sa protection en mobilité sans diminuer son champ de vision."
exports.url = "https://google.fr"
exports.capacité = "BOUCLIER D'ARME BLINDÉ TRANSPARENT (TARS MK 0)"
exports.ext=".png"