exports.name = "Montagne"
exports.armure = "● ● ●"
exports.rapidité = "● ○ ○"
exports.description = "Vétéran de la Gendarmerie nationale, Gilles Touré est le plus ancien agent en service du GIGN. Extrêmement protecteur vis-à-vis de ses équipiers, ce gentil géant n'hésitera pas à se jeter au-devant d'une balle pour protéger un autre agent. Le grand bouclier anti-émeute dont il est équipé date des années 1980 et a connu plus de missions que la plupart des agents. Montagne est l'homme de pointe idéal pour percer les lignes ennemies : il peut étendre son bouclier afin d'être protégé de la tête aux pieds en position debout, tout en offrant un abri à ceux qui sont derrière lui."
exports.url = "https://google.fr"
exports.capacité = "LE ROCK (BOUCLIER EXTENSIBLE)"
exports.ext=".gif"